[project]
name = "pdf-split-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "pyinstaller>=6.14.1",
    "pypdf2>=3.0.1",
    "pyqt6>=6.9.1",
    "tk>=0.1.0",
]
